# Generated by Django 6.0.5 on 2026-07-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
